# Generated by Django 5.1.3 on 2024-11-20 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('medio_transporte', models.CharField(choices=[('auto', 'Auto'), ('bus', 'Bus'), ('bicicleta', 'Bicicleta'), ('a pie', 'A pie')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroKilometraje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('kilometros_recorridos', models.FloatField()),
                ('medio_transporte', models.CharField(choices=[('auto', 'Auto'), ('bus', 'Bus'), ('bicicleta', 'Bicicleta'), ('a pie', 'A pie')], max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jueguitoAutos.usuario')),
            ],
        ),
    ]
