# Generated by Django 5.1.3 on 2024-11-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jueguitoAutos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='huella_carbono_total',
            field=models.FloatField(default=0.0),
        ),
    ]
